// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW0hrM1sIKOq7b9nxwVhLZqob71K0wl1w',
    appId: '1:117458452285:web:3b3f0fd9178a35712f4f54',
    messagingSenderId: '117458452285',
    projectId: 'dakshin-test',
    authDomain: 'dakshin-test.firebaseapp.com',
    storageBucket: 'dakshin-test.appspot.com',
    measurementId: 'G-GSRZCGHT6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwSfMsiMDdhg4o6hmRFmnI6xpvXjl4qY',
    appId: '1:117458452285:android:fe58db6c492392cf2f4f54',
    messagingSenderId: '117458452285',
    projectId: 'dakshin-test',
    storageBucket: 'dakshin-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl_SYP6tmYThIiUeZwqbu-COXxiVfjpYs',
    appId: '1:117458452285:ios:f2563da10ffab2052f4f54',
    messagingSenderId: '117458452285',
    projectId: 'dakshin-test',
    storageBucket: 'dakshin-test.appspot.com',
    iosClientId: '117458452285-dvpq5b4u4jkun36kj9vdjq0h5hj742s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl_SYP6tmYThIiUeZwqbu-COXxiVfjpYs',
    appId: '1:117458452285:ios:f2563da10ffab2052f4f54',
    messagingSenderId: '117458452285',
    projectId: 'dakshin-test',
    storageBucket: 'dakshin-test.appspot.com',
    iosClientId: '117458452285-dvpq5b4u4jkun36kj9vdjq0h5hj742s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
